---
title: "Passwords"
output: html_notebook
---

# Introduction/Overview of the Problem or Question
The utilization of the "Bad Passwords" data frame is particularly pertinent given the ubiquity of passwords in everyday user interactions. This dataset, meticulously curated and formatted by [Sujay Kapadnis](https://www.kaggle.com/sujaykapadnis) from an external source called "[Information is Beautiful](https://docs.google.com/spreadsheets/d/1cz7TDhm0ebVpySqbTvrHrD3WpxeyE4hLZtifWSnoNTQ/edit#gid=21)," offers a comprehensive collection of data values. The incorporation of [tidytuesdayR library](https://thebioengineer.github.io/tidytuesdayR/) has ensured that the data is structured in a tidy format, enhancing its accessibility and interpretability.

By leveraging this data set, the objective is to discern patterns and characteristics associated with commonly used passwords, thereby contributing insights into the decision-making process surrounding password security. Furthermore, the examination of this data will shed light on whether the findings support or provide a foundational basis for advocating the use of randomly generated passkeys over conventional passwords. This exploration aligns with the broader discourse on enhancing cyber security measures and underscores the practical implications of password-related decision-making.

It appears that Sujay Kapadnis curated this data set with the intention of offering a compilation of passwords deemed extremely common and, consequently, "bad" choices for users. The data set, comprising 507 observations across 9 distinct variables, provides valuable information for individuals seeking to enhance their password security practices.

```{r}
str(passwords)
```

The variables include the rank of the password, with the most common and vulnerable passwords marked as 1. Additionally, the dataset encompasses the password itself, the categorical classification indicating the type of password, the time complexity estimation for cracking each password, the strength rating, and the associated font size. These attributes collectively afford a comprehensive understanding of the vulnerabilities associated with commonly used passwords, enabling users to make informed decisions about their password choices and potentially advocating for the adoption of more secure practices.

To explore the notion of a selected password contributing to its classification as a "bad password," it is essential to identify and analyze the relevant factors within the dataset. The outcome variable, in this case, could be framed as a binary variable indicating whether a password is categorized as "bad" or not. Considering the dataset's structure, I would like to designate a binary outcome variable, such as "Bad_Password," where 1 represents a password labeled as bad and 0 denotes otherwise. Subsequently, want to employ a statistical technique to investigate the relationships between different features (for example: rank, password type, time complexity, strength, etc.) and the likelihood of a password being classified as "bad."
